global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']