services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d:ro
    env_file:
      - ../.env.db
    ports:
      - "${HOST_DB_PORT:-5432}:5432"

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "${HOST_RABBITMQ_PORT:-5672}:5672"
      - "${HOST_RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    env_file:
      - ../.env.rabbitmq

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: django_api
    command: sh -c "python manage.py migrate --noinput && gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env.common
      - ../.env.web
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: celery_worker
    command: celery -A backend worker -l info
    volumes:
      - ..:/app
    env_file:
      - ../.env.common
      - ../.env.web
    depends_on:
      - web

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_gateway
    ports:
      - "${HOST_NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
