# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('classificadores', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create table for job processamento
            CREATE TABLE IF NOT EXISTS movimento_jobs_processamento (
                jbp_id BIGSERIAL PRIMARY KEY,
                jbp_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                jbp_arquivo_original VARCHAR(100) NOT NULL,
                jbp_dt_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                jbp_dt_alteracao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                jbp_usr_criacao INTEGER,
                jbp_usr_alteracao INTEGER,
                jbp_dt_conclusao TIMESTAMPTZ,
                jbp_mensagem_erro TEXT,
                emp_id BIGINT,
                clf_id_status BIGINT NOT NULL
            );

            -- Add foreign keys if they don't exist
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_jbp_empresa' AND conrelid = 'movimento_jobs_processamento'::regclass
                ) THEN
                    ALTER TABLE movimento_jobs_processamento
                        ADD CONSTRAINT fk_jbp_empresa FOREIGN KEY (emp_id)
                        REFERENCES cadastro_empresas (emp_id) ON DELETE RESTRICT;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_jbp_status' AND conrelid = 'movimento_jobs_processamento'::regclass
                ) THEN
                    ALTER TABLE movimento_jobs_processamento
                        ADD CONSTRAINT fk_jbp_status FOREIGN KEY (clf_id_status)
                        REFERENCES geral_classificadores (clf_id) ON DELETE RESTRICT;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS movimento_jobs_processamento;
            """,
        ),
    ]
