# Generated by Django 4.2 on 2025-10-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processamento", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprocessamento",
            name="hash_arquivo",
            field=models.CharField(
                blank=True,
                db_column="jbp_hash_arquivo",
                db_index=True,
                max_length=64,
                null=True,
            ),
        ),
    ]
