# Generated by Django 4.2 on 2025-10-12 19:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_initial'),
        ('classificadores', '0003_initial'),
        ('processamento', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProcessamento',
            fields=[
                ('id', models.BigAutoField(db_column='jbp_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='jbp_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo_original', models.FileField(db_column='jbp_arquivo_original', upload_to='notas_fiscais_uploads/')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, db_column='jbp_dt_criacao')),
                ('dt_alteracao', models.DateTimeField(auto_now=True, db_column='jbp_dt_alteracao')),
                ('usr_criacao', models.IntegerField(blank=True, db_column='jbp_usr_criacao', null=True)),
                ('usr_alteracao', models.IntegerField(blank=True, db_column='jbp_usr_alteracao', null=True)),
                ('dt_conclusao', models.DateTimeField(blank=True, db_column='jbp_dt_conclusao', null=True)),
                ('mensagem_erro', models.TextField(blank=True, db_column='jbp_mensagem_erro', null=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='empresa.minhaempresa')),
                ('status', models.ForeignKey(db_column='clf_id_status', on_delete=django.db.models.deletion.PROTECT, related_name='jobs_status', to='classificadores.classificador')),
            ],
            options={
                'db_table': 'movimento_jobs_processamento',
            },
        ),
    ]
