# Generated by Django 4.2 on 2025-10-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_empresanaoclassificada_id_and_more'),
        ('processamento', '0003_add_hash_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprocessamento',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='emp_cnpj_numero', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='empresa.minhaempresa'),
        ),
    ]
