# Generated by Django 4.2 on 2025-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprocessamento',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=models.deletion.PROTECT, related_name='jobs', to='empresa.minhaempresa'),
        ),
    ]
