# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classificadores', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create table for parceiros
            CREATE TABLE IF NOT EXISTS cadastro_parceiros (
                pcr_id BIGSERIAL PRIMARY KEY,
                pcr_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                pcr_nome VARCHAR(255) NOT NULL,
                pcr_cnpj VARCHAR(18) NOT NULL UNIQUE,
                clf_id_tipo BIGINT NOT NULL
            );

            -- Add foreign key if it doesn't exist
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_pcr_tipo' AND conrelid = 'cadastro_parceiros'::regclass
                ) THEN
                    ALTER TABLE cadastro_parceiros
                        ADD CONSTRAINT fk_pcr_tipo FOREIGN KEY (clf_id_tipo)
                        REFERENCES geral_classificadores (clf_id) ON DELETE RESTRICT;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS cadastro_parceiros;
            """,
        ),
    ]
