# Generated by Django 4.2 on 2025-10-12 19:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classificadores', '0003_initial'),
        ('parceiros', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(db_column='pcr_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='pcr_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_column='pcr_nome', max_length=255)),
                ('cnpj', models.CharField(db_column='pcr_cnpj', max_length=18, unique=True)),
                ('clf_tipo', models.ForeignKey(db_column='clf_id_tipo', on_delete=django.db.models.deletion.PROTECT, related_name='parceiros_tipo', to='classificadores.classificador')),
            ],
            options={
                'db_table': 'cadastro_parceiros',
            },
        ),
    ]
