# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classificadores', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create table for lancamentos financeiros
            CREATE TABLE IF NOT EXISTS movimento_lancamentos_financeiros (
                lcf_id BIGSERIAL PRIMARY KEY,
                lcf_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                lcf_descricao VARCHAR(255) NOT NULL,
                lcf_valor DECIMAL(10, 2) NOT NULL,
                lcf_data_vencimento DATE NOT NULL,
                lcf_data_pagamento DATE,
                lcf_dt_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                lcf_dt_alteracao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                lcf_usr_criacao INTEGER,
                lcf_usr_alteracao INTEGER,
                clf_id_status BIGINT NOT NULL,
                clf_id_tipo BIGINT NOT NULL,
                ntf_id BIGINT NOT NULL UNIQUE
            );

            -- Add foreign keys if they don't exist
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_lcf_status' AND conrelid = 'movimento_lancamentos_financeiros'::regclass
                ) THEN
                    ALTER TABLE movimento_lancamentos_financeiros
                        ADD CONSTRAINT fk_lcf_status FOREIGN KEY (clf_id_status)
                        REFERENCES geral_classificadores (clf_id) ON DELETE RESTRICT;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_lcf_tipo' AND conrelid = 'movimento_lancamentos_financeiros'::regclass
                ) THEN
                    ALTER TABLE movimento_lancamentos_financeiros
                        ADD CONSTRAINT fk_lcf_tipo FOREIGN KEY (clf_id_tipo)
                        REFERENCES geral_classificadores (clf_id) ON DELETE RESTRICT;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_lcf_nota_fiscal' AND conrelid = 'movimento_lancamentos_financeiros'::regclass
                ) THEN
                    ALTER TABLE movimento_lancamentos_financeiros
                        ADD CONSTRAINT fk_lcf_nota_fiscal FOREIGN KEY (ntf_id)
                        REFERENCES movimento_notas_fiscais (ntf_id) ON DELETE CASCADE;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS movimento_lancamentos_financeiros;
            """,
        ),
    ]
