# Generated by Django 4.2 on 2025-10-13 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classificadores", "0002_initial"),
        ("notas", "0002_initial"),
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="lcf_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="lcf_uuid",
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(db_column="lcf_descricao", max_length=255),
                ),
                (
                    "valor",
                    models.DecimalField(
                        db_column="lcf_valor", decimal_places=2, max_digits=10
                    ),
                ),
                ("data_vencimento", models.DateField(db_column="lcf_data_vencimento")),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, db_column="lcf_data_pagamento", null=True
                    ),
                ),
                (
                    "dt_criacao",
                    models.DateTimeField(auto_now_add=True, db_column="lcf_dt_criacao"),
                ),
                (
                    "dt_alteracao",
                    models.DateTimeField(auto_now=True, db_column="lcf_dt_alteracao"),
                ),
                (
                    "usr_criacao",
                    models.IntegerField(
                        blank=True, db_column="lcf_usr_criacao", null=True
                    ),
                ),
                (
                    "usr_alteracao",
                    models.IntegerField(
                        blank=True, db_column="lcf_usr_alteracao", null=True
                    ),
                ),
                (
                    "clf_status",
                    models.ForeignKey(
                        db_column="clf_id_status",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos_status",
                        to="classificadores.classificador",
                    ),
                ),
                (
                    "clf_tipo",
                    models.ForeignKey(
                        db_column="clf_id_tipo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos_tipo",
                        to="classificadores.classificador",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.OneToOneField(
                        db_column="ntf_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamento",
                        to="notas.notafiscal",
                    ),
                ),
            ],
            options={
                "db_table": "movimento_lancamentos_financeiros",
            },
        ),
    ]
