# Generated by Django 4.2 on 2025-10-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0003_initial'),
        ('notas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='nota_fiscal',
            field=models.OneToOneField(db_column='ntf_id', on_delete=django.db.models.deletion.CASCADE, related_name='lancamento', to='notas.notafiscal'),
        ),
    ]
