# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificador',
            fields=[
                ('id', models.BigAutoField(db_column='clf_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='clf_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(db_column='clf_tipo', max_length=50)),
                ('codigo', models.CharField(db_column='clf_codigo', max_length=50)),
                ('descricao', models.CharField(db_column='clf_descricao', max_length=255)),
            ],
            options={
                'db_table': 'geral_classificadores',
                'unique_together': {('tipo', 'codigo')},
            },
        ),
    ]
