# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create table for classificadores
            CREATE TABLE IF NOT EXISTS geral_classificadores (
                clf_id BIGSERIAL PRIMARY KEY,
                clf_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                clf_tipo VARCHAR(50) NOT NULL,
                clf_codigo VARCHAR(50) NOT NULL,
                clf_descricao VARCHAR(255) NOT NULL,
                UNIQUE(clf_tipo, clf_codigo)
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS geral_classificadores;
            """,
        ),
    ]
