# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processamento', '0001_initial'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(db_column='ntf_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='ntf_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('chave_acesso', models.CharField(blank=True, db_column='ntf_chave_acesso', max_length=44, null=True, unique=True)),
                ('numero', models.CharField(db_column='ntf_numero', max_length=100)),
                ('data_emissao', models.DateField(db_column='ntf_data_emissao')),
                ('valor_total', models.DecimalField(db_column='ntf_valor_total', decimal_places=2, max_digits=12)),
                ('job_origem', models.ForeignKey(db_column='jbp_id', on_delete=django.db.models.deletion.PROTECT, to='processamento.jobprocessamento')),
                ('parceiro', models.ForeignKey(db_column='pcr_id', on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='parceiros.parceiro')),
            ],
            options={
                'db_table': 'movimento_notas_fiscais',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalItem',
            fields=[
                ('id', models.BigAutoField(db_column='nfi_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='nfi_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(db_column='nfi_descricao', max_length=255)),
                ('quantidade', models.DecimalField(db_column='nfi_quantidade', decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(db_column='nfi_valor_unitario', decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(db_column='nfi_valor_total', decimal_places=2, max_digits=12)),
                ('nota_fiscal', models.ForeignKey(db_column='ntf_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='notas.notafiscal')),
            ],
            options={
                'db_table': 'movimento_nota_fiscal_itens',
            },
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['nota_fiscal'], name='idx_nfi_ntf'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['parceiro', 'data_emissao'], name='idx_ntf_parc_data'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['parceiro', 'numero'], name='idx_ntf_parc_num'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_acesso__isnull', True)), fields=('parceiro', 'numero'), name='uq_ntf_parceiro_numero_when_no_chave'),
        ),
    ]
