# Generated by Django 4.2 on 2025-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_add_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='chave_acesso',
            field=models.CharField(blank=True, db_column='ntf_chave_acesso', max_length=44, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['parceiro', 'data_emissao'], name='idx_ntf_parc_data'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['parceiro', 'numero'], name='idx_ntf_parc_num'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['nota_fiscal'], name='idx_nfi_ntf'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_acesso__isnull', True)), fields=('parceiro', 'numero'), name='uq_ntf_parceiro_numero_when_no_chave'),
        ),
    ]
