# Generated by Django 4.2 on 2025-10-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0003_initial'),
        ('parceiros', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='parceiro',
            field=models.ForeignKey(db_column='pcr_id', on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='parceiros.parceiro'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['nota_fiscal'], name='idx_nfi_ntf'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['parceiro', 'data_emissao'], name='idx_ntf_parc_data'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['parceiro', 'numero'], name='idx_ntf_parc_num'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_acesso__isnull', True)), fields=('parceiro', 'numero'), name='uq_ntf_parceiro_numero_when_no_chave'),
        ),
    ]
