# Generated by Django 4.2 on 2025-10-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Enable the pgcrypto extension for UUID generation if it's not already enabled.
            CREATE EXTENSION IF NOT EXISTS pgcrypto;

            -- Create the main table for the company.
            CREATE TABLE IF NOT EXISTS cadastro_empresas (
                emp_id BIGSERIAL PRIMARY KEY,
                emp_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                emp_nome VARCHAR(255) NOT NULL DEFAULT 'Minha Empresa',
                emp_cnpj VARCHAR(18) NOT NULL UNIQUE,
                emp_senha_hash VARCHAR(128) DEFAULT '',
                emp_dt_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                emp_dt_alteracao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                emp_usr_criacao INTEGER,
                emp_usr_alteracao INTEGER,
                emp_dt_exclusao TIMESTAMPTZ
            );

            -- Create table for empresas_nao_classificadas
            CREATE TABLE IF NOT EXISTS empresas_nao_classificadas (
                enc_id BIGSERIAL PRIMARY KEY,
                enc_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                enc_cnpj VARCHAR(18) NOT NULL UNIQUE,
                enc_nome_fantasia VARCHAR(255) NOT NULL,
                enc_razao_social VARCHAR(255) NOT NULL,
                enc_uf VARCHAR(2) NOT NULL,
                enc_cidade VARCHAR(255) NOT NULL,
                enc_logradouro VARCHAR(255) NOT NULL,
                enc_numero VARCHAR(255) NOT NULL,
                enc_bairro VARCHAR(255) NOT NULL,
                enc_cep VARCHAR(9) NOT NULL,
                enc_telefone VARCHAR(20) NOT NULL,
                enc_email VARCHAR(255) NOT NULL,
                enc_dt_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS empresas_nao_classificadas;
            DROP TABLE IF EXISTS cadastro_empresas;
            """,
        ),
    ]
