# Generated by Django 4.2 on 2025-10-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresanaoclassificada',
            name='id',
        ),
        migrations.RemoveField(
            model_name='minhaempresa',
            name='id',
        ),
        migrations.AddField(
            model_name='empresanaoclassificada',
            name='cnpj_numero',
            field=models.BigIntegerField(db_column='enc_cnpj_numero', default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='minhaempresa',
            name='cnpj_numero',
            field=models.BigIntegerField(db_column='emp_cnpj_numero', default=0, primary_key=True, serialize=False),
        ),
    ]
