# Generated by Django 4.2 on 2025-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_add_senha_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minhaempresa',
            options={'verbose_name_plural': 'Minha Empresa'},
        ),
        migrations.AddField(
            model_name='minhaempresa',
            name='senha_hash',
            field=models.CharField(blank=True, db_column='emp_senha_hash', default='', max_length=128),
        ),
    ]
