# Generated by Django 4.2 on 2025-10-13 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Create table for notifications
            CREATE TABLE IF NOT EXISTS notifications_notification (
                ntf_id BIGSERIAL PRIMARY KEY,
                ntf_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                title VARCHAR(255) NOT NULL,
                body TEXT NOT NULL,
                data JSONB,
                delivered BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                delivered_at TIMESTAMPTZ,
                user_id INTEGER NOT NULL
            );

            -- Create table for devices
            CREATE TABLE IF NOT EXISTS notifications_device (
                dvc_id BIGSERIAL PRIMARY KEY,
                dvc_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                token VARCHAR(512) NOT NULL UNIQUE,
                platform VARCHAR(16),
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                empresa_id BIGINT,
                user_id INTEGER
            );

            -- Add foreign keys if they don't exist
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_ntf_user' AND conrelid = 'notifications_notification'::regclass
                ) THEN
                    ALTER TABLE notifications_notification
                        ADD CONSTRAINT fk_ntf_user FOREIGN KEY (user_id)
                        REFERENCES auth_user (id) ON DELETE CASCADE;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_dvc_user' AND conrelid = 'notifications_device'::regclass
                ) THEN
                    ALTER TABLE notifications_device
                        ADD CONSTRAINT fk_dvc_user FOREIGN KEY (user_id)
                        REFERENCES auth_user (id) ON DELETE CASCADE;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'fk_dvc_empresa' AND conrelid = 'notifications_device'::regclass
                ) THEN
                    ALTER TABLE notifications_device
                        ADD CONSTRAINT fk_dvc_empresa FOREIGN KEY (empresa_id)
                        REFERENCES cadastro_empresas (emp_id) ON DELETE CASCADE;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS notifications_device;
            DROP TABLE IF EXISTS notifications_notification;
            """,
        ),
    ]
