# Test comment for notifications rebuild
# Generated by Django 4.2 on 2025-10-11 01:07

import os
from django.conf import settings
from django.db import migrations

def read_sql_file(file_name):
    """Reads the specified SQL file from the migrations directory."""
    file_path = os.path.join(os.path.dirname(__file__), file_name)
    with open(file_path, 'r') as f:
        return f.read()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=read_sql_file('0002_initial.sql'),
            reverse_sql="""
            DROP TABLE IF EXISTS notifications_device;
            DROP TABLE IF EXISTS notifications_notification;
            """,
        ),
    ]
