# Generated by Django 4.2 on 2025-10-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
    ]
